dist: trusty
env:
  - IMAGE_TAG=latest CONTEXT=./7.4/
  - IMAGE_TAG=7.4 CONTEXT=./7.4/
  - IMAGE_TAG=7.3 CONTEXT=./7.3/
  - IMAGE_TAG=7.2 CONTEXT=./7.2/
  - IMAGE_TAG=7.1 CONTEXT=./7.1/
  - IMAGE_TAG=7.0 CONTEXT=./7.0/

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - IMAGE="${DOCKER_ACCOUNT}/composer:${IMAGE_TAG}"
  - docker build -t $IMAGE $CONTEXT
  - docker images
  - docker push $IMAGE
